// roots_store.h — built-in trust store kept in flash.
// Generated by tools/roots2c.py from certs/roots.pem: concatenated DER
// certificates + an index sorted by the FNV-1a hash of each subject. Portable,
// host-tested (validation/host-tests/test_roots_store.c).
#ifndef ROOTS_STORE_H
#define ROOTS_STORE_H
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

struct roots_entry {
    uint32_t hash;        // FNV-1a 32-bit of the subject (raw DER)
    uint32_t der_off;     // certificate start in roots_store.der
    uint16_t der_len;
    uint16_t subj_off;    // subject offset, relative to the certificate start
    uint16_t subj_len;
    const char *name;     // CN (else OU, else O), ASCII
};

struct roots_store {
    const uint8_t *der;
    uint32_t der_size;
    const struct roots_entry *e;   // sorted by ascending hash
    int count;
};

// Roots compiled into the firmware (certs/roots.pem). Used when no CA was
// uploaded with AT$CA= (an uploaded CA replaces this store).
extern const struct roots_store roots_store;

uint32_t roots_hash(const uint8_t *p, size_t n);

// Indexes (into s->e) of the roots whose subject equals name (raw DER), at
// most max; returns how many were written to idx.
int roots_find(const struct roots_store *s, const uint8_t *name, size_t n, int *idx, int max);

// Index of the root whose DER starts at p, -1 if p is not in s.
int roots_index_of(const struct roots_store *s, const uint8_t *p);

#ifdef __cplusplus
}
#endif

#endif
