# build_id.cmake — run on EVERY build (target fw_build_id): writes OUT
# (build_id.h) from the repository state, and rewrites it only when it
# changes, so nothing is rebuilt needlessly. Everything comes from git, never
# from the build clock, so the same commit always gives the same UF2:
#   FW_BUILD       `git describe`: vX.Y.Z for a release, vX.Y.Z-N-gSHA[-dirty] otherwise
#   FW_BUILD_DATE  commit date, UTC, C locale ("Sep 24 2026 17:03:48 UTC")
#   BUILD_EPOCH    commit date as a UNIX epoch: clock floor before SNTP (time_support.h)
#   cmake -DSRC=<repo root> -DOUT=<file> -P build_id.cmake
execute_process(
      COMMAND git describe --tags --always --dirty --match "v[0-9]*"
      WORKING_DIRECTORY ${SRC}
      OUTPUT_VARIABLE id OUTPUT_STRIP_TRAILING_WHITESPACE
      RESULT_VARIABLE rc ERROR_QUIET)
if(NOT rc EQUAL 0 OR id STREQUAL "")
      set(id "unknown")
endif()
execute_process(
      COMMAND ${CMAKE_COMMAND} -E env TZ=UTC LC_ALL=C git log -1 --format=%cd "--date=format-local:%b %d %Y %H:%M:%S"
      WORKING_DIRECTORY ${SRC}
      OUTPUT_VARIABLE date OUTPUT_STRIP_TRAILING_WHITESPACE
      RESULT_VARIABLE rc ERROR_QUIET)
if(NOT rc EQUAL 0 OR date STREQUAL "")
      set(date "unknown")
else()
      set(date "${date} UTC")
endif()
execute_process(
      COMMAND git log -1 --format=%ct
      WORKING_DIRECTORY ${SRC}
      OUTPUT_VARIABLE epoch OUTPUT_STRIP_TRAILING_WHITESPACE
      RESULT_VARIABLE rc ERROR_QUIET)
if(NOT rc EQUAL 0 OR NOT epoch MATCHES "^[0-9]+$")
      set(epoch "1735689600")   # 2025-01-01, same fallback as time_support.h
endif()
set(content "// Generated by cmake/build_id.cmake — do not edit.\n#define FW_BUILD \"${id}\"\n#define FW_BUILD_DATE \"${date}\"\n#define BUILD_EPOCH ${epoch}UL\n")
if(EXISTS ${OUT})
      file(READ ${OUT} old)
endif()
if(NOT "${old}" STREQUAL "${content}")
      file(WRITE ${OUT} "${content}")
endif()
